name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .[dev]

      - name: Lint
        run: |
          python -m ruff check tool

      - name: Test
        run: |
          python -m pytest

      - name: Type check
        run: |
          python -m mypy tool

      - name: Build release archive
        run: |
          python -m tool.cli package --version ${{ github.ref_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: portable-profile
          path: release/portable-profile.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/portable-profile.zip
            release/portable-profile.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
